Minor updates
groggyegg/plugin.video.dramacool pull request #41
Opened 2022-09-23 17:36 UTC by MoojMidge

Made a few changes to make this plugin a little easier to use for me:
- Fixed up some sort methods that didn't work previously
- Added some icons for pagination
- Added a setting to auto-select a preferred server to use for streaming

PR for your consideration.

2022-10-02 12:47 UTC, groggyegg requested changes
Have briefly looked through it and it looks good overall. Just some parts that needs to be investigated.

2022-10-02 12:47 UTC, groggyegg commented on dramacool/database.py
> +            dateadded = str(now - timedelta(minutes=minutes, hours=hours, days=days))
What is dateadded used for?

2022-10-02 12:47 UTC, groggyegg commented on dramacool/database.py
> +            year = year.group(1) if year else ''
Probably not needed since year will most likely exist in kwargs if it exist on the title. Also, sometimes it's handled manually.

2022-10-02 12:47 UTC, groggyegg commented on dramacool/addon.py
> +}
Has this been tested with different skins and resolutions?

2022-10-02 12:47 UTC, groggyegg commented on resources/settings.xml
> +		<setting label="33506" type="labelenum" id="preferredServer" lvalues="33507|33508|33509|33510|33511|33512|33513|33514" default="2"/>
Seems to be a bit of a code smell if we have this `# Literal server name - do not translate`
Is it possible to use enum instead?

2022-10-02 14:28 UTC, MoojMidge commented on dramacool/database.py
> +            dateadded = str(now - timedelta(minutes=minutes, hours=hours, days=days))
The recently added listings are sorted, by default, by when they are added to the website and the listings are created in this order. To maintain this original order, the listing must remain unsorted using SORT_METHOD_UNSORTED.

Changing the sort order to something else e.g. SORT_METHOD_LABEL_IGNORE_THE, will mean that the original default unsorted sort order is permanently lost.

In order to restore the original sort order it must be replicated using SORT_METHOD_DATEADDED which requires that the ListItem videoinfo has a dateadded value.

2022-10-02 14:34 UTC, MoojMidge commented on dramacool/database.py
> +            year = year.group(1) if year else ''
I couldn't see anywhere the year was actually passed through on any of the normal listings, even when SORT_METHOD_VIDEO_YEAR was previously being used. It only seemed to be used when the filter was used.

Because it was missing the sort method just didn't work.

2022-10-02 14:48 UTC, MoojMidge commented on dramacool/addon.py
> +}
Looks fine in Estuary, Embuary, and Arctic Horizon 2, all at 1080p.

The icons themselves have been added to the plugin so they will always be available, regardless of the skin.

The resolution of the icons are 128 x 128 px, which is smaller than any normal artwork type that Kodi uses, including the poster artwork that is used in this plugin. So worst case the icons will look a bit blurry, or may appear stretched or skewed, depending on how a skin chooses to scale the icon artwork type.

From what I can see most skins don't try to do anything too fancy to icon type artwork.

2022-10-02 14:51 UTC, MoojMidge commented on resources/settings.xml
> +		<setting label="33506" type="labelenum" id="preferredServer" lvalues="33507|33508|33509|33510|33511|33512|33513|33514" default="2"/>
The server name is needed in the code, so a list of server names that contains the equivalent original/untranslated lvalues of the enum would be needed, that could then be indexed with the enum setting value.

Worst case if someone does translate the server name(s) when using a labelenum, the auto-selection doesn't work, but the manual selection will still be used.

Just thought it would be neater using the labelenum, rather than having the server names defined in two places, but if you prefer using an enum, I can do that instead.

2022-11-04 19:03 UTC, groggyegg commented
I will put this on hold, I'm not sure if I want this integrated as the list would need to be maintained when any server gets added or removed which I am reluctant to do.

2022-11-05 02:44 UTC, MoojMidge commented
Fair enough.

Note though, that the list of servers in the PR is just used to pick a preferred server from the list of servers scraped from the site.

If the preferred server doesn't exist, or the list of servers on the site changes, this will still be scraped and presented to the user as a list where they can select which server to use so there is no real need to update the addon, it would just function the same way it currently does without the preferred server being used.

This actually already happens because not all series, especially older ones, have the same available servers. So if a preferred server is selected that is not available for a series, the server list is just shown as normal, for the user to select and play the video.

Shall I just close the PR? Or maybe I can add an additional setting where the user can type in their preferred server name in addition to choosing one of the pre-defined servers? This way the user can always change their preferred server to reflect what is shown on the site, if it does change.

2022-11-07 16:52 UTC, groggyegg commented
You can leave it open, I will look into when I have time, probably around late December when I have vacation. Some parts of the code could be added but not sure about the rest.

Regarding preferred server, if you want it to be merged then either you or someone else have to keep it updated in repository. Since issues will probably be created when server does not exist in the list.

2022-11-07 21:55 UTC, MoojMidge commented
All good, I can always maintain this for personal use, so no issues if you don't wan't to merge some, or all of this.

When you have a chance to review further, you can see what happens when the preferred server is not available.

As mentioned, there is no error that occurs, or any issue which will require regular changes/additions/removals from the preferred server list - the scraped server list is always used and presented to the user if the preferred server cannot be found - exactly the same as what happens now.

The preferred server selection is optional anyway, so it can just be turned off, and the scraped server list will always be shown.

When I have a bit more time, I will add a custom preferred server option anyway, so that a preferred server name can be typed in by the user if something changes, in addition to selecting from a pre-defined list.

2023-07-09 09:17 UTC, groggyegg commented
Closing this since it will most likely not be merged.

2023-07-09 09:17 UTC, closed without merging